FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY node.conf /etc/nginx/conf.d

RUN mkdir /var/www/node/public -p && touch /var/www/node/public/index.js

ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "nginx", "-g", "daemon off;" ]

